### ISSUE TITLE
Encrypt & Decrypt Emails In The Database

### ISSUE THREAD

**Issue by 9mido** [saadmk11/django-newsfeed#8]
There should be a way to encrypt/decrypt emails in the database because emails fall into GDPR / PII / Privacy laws. Perhaps using a database setting like NEWSFEED_EMAIL_ENCRYPT = True|False would enable/disable this feature. This way if your database was ever stolen/hacked, the attacker would not be able to see the emails. 

But If someone changes this setting later on the user would probably need to do some sort of data migrations. https://docs.djangoproject.com/en/3.1/howto/writing-migrations/ which is not really desirable. Unless it can somehow get built into the app?

SELECT SQL queries and django get() should be able to view the decrypted emails. 

Some ideas would be to do something like django-fernet-fields which uses the SECRET_KEY to do both the encryption and decryption. Or if you are using postgres, do something like django-pgcrypto-fields which uses a postgres pgcrypto extension.

**Comment by saadmk11** [comment]
As far as I know GDPR does not require email addresses to be encrypted. But I'm not based on any EU countries. So, I don't have much to say about it.
