### ISSUE TITLE
Emails Not Sending

### ISSUE THREAD

**Issue by 9mido** [saadmk11/django-newsfeed#9]
When on /newsfeed/subscribe/ and I type in an email address, the emails do not get sent to that email address. 

Is this because I did not set up celery?

**Comment by saadmk11** [comment]
Did you set the email settings required by django on the settings file. Something similar to this:
https://github.com/saadmk11/django-newsfeed/blob/ce2cac9ccf3d863bc604d3868ff5f992fb22a4eb/test_project/settings.py#L124 


More details here: https://docs.djangoproject.com/en/3.1/ref/settings/#email-backend

**Comment by 9mido** [comment]
Yes I did.
